import { createFileRoute, Link } from "@tanstack/react-router";
import heroImg from "@/assets/superfood-hero-kaffee.jpg";
import { EditorialChapter, EvidenceStrip } from "@/components/site/EditorialEvidence";
import { useLocale } from "@/i18n/LocaleProvider";

export const Route = createFileRoute("/superfood/ursprung")({
  head: () => ({ meta: [
    { title: "Ursprung & Rückverfolgbarkeit — ZONES SUPERFOOD" },
    { name: "description", content: "Beschaffung, Rückverfolgbarkeit und produktbezogene Zertifizierungen bei ZONES SUPERFOOD." },
    { property: "og:title", content: "Ursprung & Rückverfolgbarkeit — ZONES SUPERFOOD" },
    { property: "og:description", content: "Wie ZONES SUPERFOOD Herkunft, Lots und Zertifizierungen dokumentiert." },
    { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: OriginPage,
});

function OriginPage() {
  const { locale } = useLocale();
  const copy = {
    de: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "QUALITÄT IST EIN DATENSATZ.", lead: "Herkunft ist kein Erzählstoff. Verarbeitung, Qualitätsstufe, Format und Charge bilden gemeinsam das, was wir belegen können.", coop: "Beschaffung", coopBody: "Wir arbeiten auf langfristige Beziehungen zu Erzeugergemeinschaften hin. Regionen und konkrete Partner werden erst genannt, wenn Lieferbeziehung und Freigabe dokumentiert sind — vorher nicht.", trace: "Rückverfolgbarkeit", traceBody: "Jedes Verkaufs-Lot soll Verarbeitung, Abfüllung und relevante Prüfdokumente zusammenführen. Produktseiten werden mit den finalen Chargendaten ergänzt.", cert: "Zertifizierungen", certBody: "EU-Bio, Fairtrade oder vergleichbare Standards werden ausschließlich am konkreten Produkt und Lot ausgewiesen. Eine Herkunftsgeschichte ersetzt kein Zertifikat.", back: "Produkte entdecken" },
    en: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "QUALITY IS A DATA SET.", lead: "Origin is not a story. Processing, quality grade, format and lot together define what we can evidence.", coop: "Sourcing", coopBody: "We work towards long-term relationships with producer communities. Regions and specific partners are named only once supply and permission are documented — not before.", trace: "Traceability", traceBody: "Each sales lot should connect processing, packing and relevant documents. Product pages will carry final batch data.", cert: "Certifications", certBody: "EU Organic, Fairtrade or comparable standards are stated only for the specific product and lot. A story never replaces a certificate.", back: "Discover products" },
    fr: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "LA QUALITÉ EST UN ENSEMBLE DE DONNÉES.", lead: "L’origine n’est pas un récit. Procédé, niveau de qualité, format et lot définissent ce que nous pouvons prouver.", coop: "Approvisionnement", coopBody: "Nous visons des relations durables avec les communautés productrices. Régions et partenaires ne sont nommés qu’après documentation.", trace: "Traçabilité", traceBody: "Chaque lot doit relier transformation, conditionnement et documents pertinents.", cert: "Certifications", certBody: "Bio UE, Fairtrade ou standards comparables ne sont indiqués que pour le produit et le lot concernés.", back: "Découvrir les produits" },
    it: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "LA QUALITÀ È UN INSIEME DI DATI.", lead: "L’origine non è un racconto. Processo, livello di qualità, formato e lotto definiscono ciò che possiamo documentare.", coop: "Approvvigionamento", coopBody: "Lavoriamo verso relazioni durature con comunità produttrici. Regioni e partner sono nominati solo se documentati.", trace: "Tracciabilità", traceBody: "Ogni lotto collega lavorazione, confezionamento e documenti rilevanti.", cert: "Certificazioni", certBody: "Bio UE, Fairtrade o standard analoghi sono indicati solo per prodotto e lotto specifici.", back: "Scopri i prodotti" },
    nl: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "KWALITEIT IS EEN DATASET.", lead: "Herkomst is geen verhaal. Verwerking, kwaliteitsniveau, formaat en lot bepalen wat we kunnen onderbouwen.", coop: "Inkoop", coopBody: "We werken aan langdurige relaties met producentengemeenschappen. Regio’s en partners worden alleen genoemd als dit gedocumenteerd is.", trace: "Traceerbaarheid", traceBody: "Elk verkooplot verbindt verwerking, verpakking en relevante documenten.", cert: "Certificeringen", certBody: "EU-biologisch, Fairtrade of vergelijkbare standaarden staan alleen bij het specifieke product en lot.", back: "Ontdek producten" },
    es: { eyebrow: "APPLIED ORIGIN SCIENCE", title: "LA CALIDAD ES UN CONJUNTO DE DATOS.", lead: "El origen no es un relato. Proceso, nivel de calidad, formato y lote definen lo que podemos acreditar.", coop: "Abastecimiento", coopBody: "Trabajamos hacia relaciones duraderas con comunidades productoras. Regiones y socios se nombran solo cuando están documentados.", trace: "Trazabilidad", traceBody: "Cada lote conecta proceso, envasado y documentación relevante.", cert: "Certificaciones", certBody: "UE ecológico, Fairtrade o estándares similares se indican solo para el producto y lote concretos.", back: "Descubrir productos" },
  }[locale];
  const sections = [["01", copy.coop, copy.coopBody], ["02", copy.trace, copy.traceBody], ["03", copy.cert, copy.certBody]];
  return <main className="bg-void pt-28 md:pt-36"><header className="relative min-h-[66svh] overflow-hidden border-b border-line"><img src={heroImg} alt="Spezialitäten-Kaffeebohnen in einer Titanschale" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover opacity-65" loading="eager" fetchPriority="high" decoding="async" /><div className="hero-wash absolute inset-0" /><div className="relative mx-auto flex min-h-[66svh] max-w-[1600px] flex-col justify-end px-6 py-16 md:px-12 md:py-24"><p className="label !text-heritage">{copy.eyebrow}</p><h1 className="mt-6 max-w-6xl font-display text-[clamp(58px,10vw,150px)] leading-[0.86]">{copy.title}</h1><p className="mt-8 max-w-2xl text-lg text-silver">{copy.lead}</p></div></header>
    <section className="py-20 md:py-28"><div className="mx-auto max-w-[1600px] px-6 md:px-12"><EvidenceStrip items={[{ value: "PROCESS", label: "01" }, { value: "GRADE", label: "02" }, { value: "FORMAT", label: "03" }, { value: "LOT", label: "04" }]} /><div className="mt-20 space-y-20">{sections.map(([index, title, body]) => <EditorialChapter key={index} index={index} eyebrow="QUALITY PROTOCOL" title={title} lead={body} />)}</div><Link to="/superfood" className="mt-20 inline-flex min-h-12 items-center bg-alpine px-7 text-xs uppercase text-primary-foreground">{copy.back} →</Link></div></section>
  </main>;
}
