/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as VersandZahlungRouteImport } from './routes/versand-zahlung'
import { Route as SmartRouteImport } from './routes/smart'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtRouteImport } from './routes/art'
import { Route as ArchitectsClubRouteImport } from './routes/architects-club'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperfoodIndexRouteImport } from './routes/superfood.index'
import { Route as ShieldLayerIndexRouteImport } from './routes/shield-layer.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories.index'
import { Route as SuperfoodUrsprungRouteImport } from './routes/superfood.ursprung'
import { Route as SuperfoodSlugRouteImport } from './routes/superfood.$slug'
import { Route as SignatureSlugRouteImport } from './routes/signature.$slug'
import { Route as ShieldLayerSlugRouteImport } from './routes/shield-layer.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as AccessoriesSlugRouteImport } from './routes/accessories.$slug'

const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const VersandZahlungRoute = VersandZahlungRouteImport.update({
  id: '/versand-zahlung',
  path: '/versand-zahlung',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartRoute = SmartRouteImport.update({
  id: '/smart',
  path: '/smart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsClubRoute = ArchitectsClubRouteImport.update({
  id: '/architects-club',
  path: '/architects-club',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperfoodIndexRoute = SuperfoodIndexRouteImport.update({
  id: '/superfood/',
  path: '/superfood/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldLayerIndexRoute = ShieldLayerIndexRouteImport.update({
  id: '/shield-layer/',
  path: '/shield-layer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/accessories/',
  path: '/accessories/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperfoodUrsprungRoute = SuperfoodUrsprungRouteImport.update({
  id: '/superfood/ursprung',
  path: '/superfood/ursprung',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperfoodSlugRoute = SuperfoodSlugRouteImport.update({
  id: '/superfood/$slug',
  path: '/superfood/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureSlugRoute = SignatureSlugRouteImport.update({
  id: '/signature/$slug',
  path: '/signature/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldLayerSlugRoute = ShieldLayerSlugRouteImport.update({
  id: '/shield-layer/$slug',
  path: '/shield-layer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesSlugRoute = AccessoriesSlugRouteImport.update({
  id: '/accessories/$slug',
  path: '/accessories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/architects-club': typeof ArchitectsClubRoute
  '/art': typeof ArtRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/protocol': typeof ProtocolRoute
  '/smart': typeof SmartRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/widerruf': typeof WiderrufRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shield-layer/$slug': typeof ShieldLayerSlugRoute
  '/signature/$slug': typeof SignatureSlugRoute
  '/superfood/$slug': typeof SuperfoodSlugRoute
  '/superfood/ursprung': typeof SuperfoodUrsprungRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shield-layer/': typeof ShieldLayerIndexRoute
  '/superfood/': typeof SuperfoodIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/architects-club': typeof ArchitectsClubRoute
  '/art': typeof ArtRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/protocol': typeof ProtocolRoute
  '/smart': typeof SmartRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/widerruf': typeof WiderrufRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shield-layer/$slug': typeof ShieldLayerSlugRoute
  '/signature/$slug': typeof SignatureSlugRoute
  '/superfood/$slug': typeof SuperfoodSlugRoute
  '/superfood/ursprung': typeof SuperfoodUrsprungRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/shield-layer': typeof ShieldLayerIndexRoute
  '/superfood': typeof SuperfoodIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/architects-club': typeof ArchitectsClubRoute
  '/art': typeof ArtRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/protocol': typeof ProtocolRoute
  '/smart': typeof SmartRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/widerruf': typeof WiderrufRoute
  '/accessories/$slug': typeof AccessoriesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/shield-layer/$slug': typeof ShieldLayerSlugRoute
  '/signature/$slug': typeof SignatureSlugRoute
  '/superfood/$slug': typeof SuperfoodSlugRoute
  '/superfood/ursprung': typeof SuperfoodUrsprungRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/shield-layer/': typeof ShieldLayerIndexRoute
  '/superfood/': typeof SuperfoodIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/architects-club'
    | '/art'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/protocol'
    | '/smart'
    | '/versand-zahlung'
    | '/widerruf'
    | '/accessories/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/shield-layer/$slug'
    | '/signature/$slug'
    | '/superfood/$slug'
    | '/superfood/ursprung'
    | '/accessories/'
    | '/journal/'
    | '/products/'
    | '/shield-layer/'
    | '/superfood/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/architects-club'
    | '/art'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/protocol'
    | '/smart'
    | '/versand-zahlung'
    | '/widerruf'
    | '/accessories/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/shield-layer/$slug'
    | '/signature/$slug'
    | '/superfood/$slug'
    | '/superfood/ursprung'
    | '/accessories'
    | '/journal'
    | '/products'
    | '/shield-layer'
    | '/superfood'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/architects-club'
    | '/art'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/protocol'
    | '/smart'
    | '/versand-zahlung'
    | '/widerruf'
    | '/accessories/$slug'
    | '/journal/$slug'
    | '/products/$slug'
    | '/shield-layer/$slug'
    | '/signature/$slug'
    | '/superfood/$slug'
    | '/superfood/ursprung'
    | '/accessories/'
    | '/journal/'
    | '/products/'
    | '/shield-layer/'
    | '/superfood/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  ArchitectsClubRoute: typeof ArchitectsClubRoute
  ArtRoute: typeof ArtRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  ProtocolRoute: typeof ProtocolRoute
  SmartRoute: typeof SmartRoute
  VersandZahlungRoute: typeof VersandZahlungRoute
  WiderrufRoute: typeof WiderrufRoute
  AccessoriesSlugRoute: typeof AccessoriesSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ShieldLayerSlugRoute: typeof ShieldLayerSlugRoute
  SignatureSlugRoute: typeof SignatureSlugRoute
  SuperfoodSlugRoute: typeof SuperfoodSlugRoute
  SuperfoodUrsprungRoute: typeof SuperfoodUrsprungRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ShieldLayerIndexRoute: typeof ShieldLayerIndexRoute
  SuperfoodIndexRoute: typeof SuperfoodIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versand-zahlung': {
      id: '/versand-zahlung'
      path: '/versand-zahlung'
      fullPath: '/versand-zahlung'
      preLoaderRoute: typeof VersandZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart': {
      id: '/smart'
      path: '/smart'
      fullPath: '/smart'
      preLoaderRoute: typeof SmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects-club': {
      id: '/architects-club'
      path: '/architects-club'
      fullPath: '/architects-club'
      preLoaderRoute: typeof ArchitectsClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superfood/': {
      id: '/superfood/'
      path: '/superfood'
      fullPath: '/superfood/'
      preLoaderRoute: typeof SuperfoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield-layer/': {
      id: '/shield-layer/'
      path: '/shield-layer'
      fullPath: '/shield-layer/'
      preLoaderRoute: typeof ShieldLayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/accessories'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superfood/ursprung': {
      id: '/superfood/ursprung'
      path: '/superfood/ursprung'
      fullPath: '/superfood/ursprung'
      preLoaderRoute: typeof SuperfoodUrsprungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superfood/$slug': {
      id: '/superfood/$slug'
      path: '/superfood/$slug'
      fullPath: '/superfood/$slug'
      preLoaderRoute: typeof SuperfoodSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature/$slug': {
      id: '/signature/$slug'
      path: '/signature/$slug'
      fullPath: '/signature/$slug'
      preLoaderRoute: typeof SignatureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield-layer/$slug': {
      id: '/shield-layer/$slug'
      path: '/shield-layer/$slug'
      fullPath: '/shield-layer/$slug'
      preLoaderRoute: typeof ShieldLayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$slug': {
      id: '/accessories/$slug'
      path: '/accessories/$slug'
      fullPath: '/accessories/$slug'
      preLoaderRoute: typeof AccessoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  ArchitectsClubRoute: ArchitectsClubRoute,
  ArtRoute: ArtRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  ProtocolRoute: ProtocolRoute,
  SmartRoute: SmartRoute,
  VersandZahlungRoute: VersandZahlungRoute,
  WiderrufRoute: WiderrufRoute,
  AccessoriesSlugRoute: AccessoriesSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ShieldLayerSlugRoute: ShieldLayerSlugRoute,
  SignatureSlugRoute: SignatureSlugRoute,
  SuperfoodSlugRoute: SuperfoodSlugRoute,
  SuperfoodUrsprungRoute: SuperfoodUrsprungRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ShieldLayerIndexRoute: ShieldLayerIndexRoute,
  SuperfoodIndexRoute: SuperfoodIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
